DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

FILEDATE_FORMAT = "%Y-%m-%d_%H-%M"

MODE_REPORT = "report"

MODE_AGG = "aggregation"

SUCCESS_STATUS_CODE = 200

CLIENT_METRIC_ERROR = 400

CLIENT_AGG_ERROR = 405

SERVER_ERROR = 500

TIMEOUT_WAITING_MESSAGE = 1

TIME_ALERT = 60 # 60 seg, 1 min

CONFIG_ALERT_FILENAME = "./app/data/config_alerts.csv" 
